[project]
name = "site_data_manager"
authors = [
    { name = "Octavision", email = "khushboo.yadav@octavision.in" }
]
description = "Site folders for Insights file uploads"
requires-python = ">=3.10"
readme = "README.md"
dynamic = ["version"]
dependencies = []

[build-system]
requires = ["flit_core >=3.4,<4"]
build-backend = "flit_core.buildapi"
